### ISSUE TITLE
How do you update the build?

### ISSUE THREAD

**Issue by rossdargan** [bastilimbach/docker-MagicMirror#7]
I've installed the docker image, but I'm warned straight away that the build is out of date. Do I need to run git pull from within the container to update it?

**Comment by bastilimbach** [comment]
Could you paste the error message? If the install steps didn't change from Magic Mirror, then there shouldn't be a problem.

**Comment by rossdargan** [comment]
This is the message I get on the front end:

MagicMirror² update available.
The current installation is 1767 commits behind on the master branch

**Comment by bastilimbach** [comment]
Hi @rossdargan, I finally found the time to look into this. I wasn't aware of the [update-notification functionality](https://github.com/MichMich/MagicMirror/tree/master/modules/default/updatenotification) of Magic Mirror. They have a default module which checks every 10 minutes if a new version is available and displays this message. You can disable this by removing the module from your config file or update the magic mirror version. This can be done using `git pull`:

```bash
docker exec -it magic_mirror sh -c 'git pull'
```

But there was still one thing, which worried me: `"I've installed the docker image, but I'm warned straight away that the build is out of date"`
So I tried it myself and you are absolutely right. The problem here is, that the docker image doesn't get build on every commit on Magic Mirrors master. I think I could overcome this problem by adding a cron job to my Travis CI configuration, which builds a new image every day. I'll do that at the weekend. **Thank you!**

**Comment by JasperZ** [comment]
Is it possible to get an updated version of the docker container on dockerhub?

**Comment by bastilimbach** [comment]
@JasperZ I try to push a newer version at the weekend. This version should then be updated every night.

**Comment by bastilimbach** [comment]
I created a cron job in travis ci, which builds and pushes a new docker image every day 👍 Now you should always get the newest MagicMirror version. Thanks again guys for reporting this issue!

**Comment by pixeye33** [comment]
Hai there,

seems its not fixed : https://hub.docker.com/r/bastilimbach/docker-magicmirror/builds/
(no new builds every day)

you could also put a git pull command in your docker-entrypoint.sh file so that every time you launch it you have the last version :)

**Comment by bastilimbach** [comment]
@pixeye33 These are the builds executed by Docker Hub. In the current setup, Docker Hub doesn't build anything. That's completely Travis job now. To see how up to date the current version is you need to look at `Last pushed: X days ago`, which should always be 1 day. I noticed the latest CRON jobs are failing because of commit [fb7e97b](https://github.com/MichMich/MagicMirror/commit/9974e35656d419d010004b026547aaaad5fa883d) from the magic mirror repo. I'll submit a PR to fix this which will make the CRON jobs succeed again.

**Comment by bastilimbach** [comment]
I created a PR to fix this issue: [#1250](https://github.com/MichMich/MagicMirror/pull/1250)

**Comment by tc60045** [comment]
I wonder if you don't have another stuck commit preventing the auto-build:
- This repo is reporting 2.6 as "latest" on fresh docker install (by docker veteran)
- MM then reports "2508 commits behind" 

`latest: Pulling from bastilimbach/docker-magicmirror
Digest: sha256:90fcd76cd419bc3a2202294c6af5924b05812df8568e7dc15460a8e4e446aefa
Status: Image is up to date for bastilimbach/docker-magicmirror:latest
f0510aafdbbf7a88150c855de37d9baaa97ef587e0d0214b99dc6aad375a465b
mmirror
Starting MagicMirror: v2.6.0`

Can you please look to see if cron jobs are the issue here?  exec'ing into containers to mess with MM git stuff is so arghhh, that I'll add "pretty please" to that last line -- with my thanks, to boot.
